liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        mercredi_thumb:
            quality: 100
            filters:
                thumbnail: { size: [250, 188], mode: inset }
