vich_uploader:
    mappings:
        mercredi_enfant_image:
            uri_prefix:         /enfants
            upload_destination: "%kernel.project_dir%/public/enfants"
            directory_namer:
                service: AcMarche\Mercredi\Namer\DirectoryNamer
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
