vich_uploader:
    mappings:
        mercredi_enfant_image:
            uri_prefix:         /files/enfants
            upload_destination: "%kernel.project_dir%/public/files/enfants"
            directory_namer:
                service: AcMarche\Mercredi\Namer\DirectoryNamer
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
        mercredi_organisation_image:
            uri_prefix:         /files/organisation
            upload_destination: "%kernel.project_dir%/public/files/organisation"
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
        mercredi_document:
            uri_prefix:         /files/documents
            upload_destination: "%kernel.project_dir%/public/files/documents"
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
