mercredi_front:
  resource: ../../src/AcMarche/Mercredi/src/Controller/Front/
  type: annotation

mercredi_admin:
  resource: ../../src/AcMarche/Mercredi/src/Controller/Admin/
  type: annotation
  prefix: admin/

mercredi_parent:
  resource: ../../src/AcMarche/Mercredi/src/Controller/Parent/
  type: annotation
  prefix: parent/
